const Products = [
    {
        id: 1,
        name:"iPhone 15 Pro Max",
        price:63990.00,
        category:"Mobile Phones & Tablets",
        description:"iPhone 15 Pro Max. Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.",
        image:"/src/assets/img/phones-tablets/iphone15promax.jpg",
    },
     {
        id: 2,
        name:"Samsung Galaxy S24 Ultra",
        price:84990.00,
        category:"Mobile Phones & Tablets",
        description:"Capture the world in unprecedented detail with Galaxy S24 Ultras 200MP camera and AI-powered Nightography. Built with a titanium frame and S Pen support.",
        image:"/src/assets/img/phones-tablets/galaxys24ultra.jpg",
    },
    {
        id: 3,
        name:"Google Pixel 8",
        price:25999.99,
        category:"Mobile Phones & Tablets",
        description:"Pixel 8 is powered by Google AI to help you do more, with the best Pixel Camera yet, powerful security features, and 7 years of software updates.",
        image:"/src/assets/img/phones-tablets/googlepixel8.jpg",
    },
    {
        id: 4,
        name:"iPad Air (M2)",
        price:44990.00,
        category:"Mobile Phones & Tablets",
        description:"iPad Air. Now supercharged by the incredibly fast Apple M2 chip. Featuring a stunning Liquid Retina display, all-day battery life, and support for Apple Pencil Pro.",
        image:"/src/assets/img/phones-tablets/ipadair.jpg",
    },
    {
        id: 5,
        name:"Xiaomi Pad 6",
        price:21999.99,
        category:"Mobile Phones & Tablets",
        description:"Xiaomi Pad 6 features a 11-inch WQHD+ 144Hz display, Snapdragon 870 processor, and lightweight design—perfect for work, creativity, and entertainment.",
        image:"/src/assets/img/phones-tablets/xiaomipad6.jpg",
    },
    {
    id: 6,
    name:"MacBook Air M3",
    price:64990.00,
    category:"Laptops & Computers",
    description:"MacBook Air with the Apple M3 chip delivers faster performance in a thin and light design, featuring a brilliant Liquid Retina display and all-day battery life.",
    image:"/assets/img/laptops-computers/MacBookAirM3.jpg",
},
{
    id: 7,
    name:"Dell XPS 13",
    price:57990.00,
    category:"Laptops & Computers",
    description:"The Dell XPS 13 combines a stunning InfinityEdge display with powerful Intel processors, all in an ultra-portable and durable design.",
    image:"/assets/img/laptops-computers/DellXP13.jpg",
},
{
    id: 8,
    name:"ASUS ROG Strix G16",
    price:89990.00,
    category:"Laptops & Computers",
    description:"ASUS ROG Strix G16 is a high-performance gaming laptop with NVIDIA GeForce RTX graphics, 13th Gen Intel processors, and a 165Hz display for smooth gameplay.",
    image:"/assets/img/laptops-computers/ASUS.jpg",
},
{
    id: 9,
    name:"Lenovo ThinkPad X1 Carbon",
    price:74990.00,
    category:"Laptops & Computers",
    description:"The Lenovo ThinkPad X1 Carbon delivers professional performance with Intel Core processors, legendary ThinkPad durability, and business-grade security features.",
    image:"/assets/img/laptops-computers/Lenovo.jpg",
},
{
    id: 10,
    name:"HP Pavilion Desktop",
    price:42990.00,
    category:"Laptops & Computers",
    description:"HP Pavilion Desktop PC offers reliable performance for everyday tasks with powerful Intel processors, modern design, and expandability options.",
    image:"/assets/img/laptops-computers/HPPavilionDesktop.jpg",
},
{
    id: 11,
    name:"Apple AirPods Pro 2",
    price:14990.00,
    category:"Audio & Wearables",
    description:"AirPods Pro (2nd Gen) feature active noise cancellation, adaptive transparency, personalized spatial audio, and a MagSafe charging case.",
    image:"",
},
{
    id: 12,
    name:"Sony WH-1000XM5",
    price:19990.00,
    category:"Audio & Wearables",
    description:"Sony WH-1000XM5 headphones provide industry-leading noise cancellation, premium sound, and up to 30 hours of battery life.",
    image:"",
},
{
    id: 13,
    name:"Samsung Galaxy Watch 6",
    price:16990.00,
    category:"Audio & Wearables",
    description:"Galaxy Watch 6 helps you stay connected and healthy with advanced fitness tracking, customizable watch faces, and seamless Galaxy ecosystem integration.",
    image:"",
},
{
    id: 14,
    name:"Fitbit Versa 4",
    price:12990.00,
    category:"Audio & Wearables",
    description:"Fitbit Versa 4 is a lightweight smartwatch with 24/7 heart rate monitoring, GPS tracking, fitness modes, and Google integration.",
    image:"",
},
{
    id: 15,
    name:"JBL Charge 5",
    price:8990.00,
    category:"Audio & Wearables",
    description:"JBL Charge 5 is a portable Bluetooth speaker with bold sound, deep bass, built-in power bank, and IP67 waterproof rating.",
    image:"",
},

{
    id: 16,
    name:"PlayStation 5",
    price:29990.00,
    category:"Gaming Gear",
    description:"PlayStation 5 delivers lightning-fast loading, immersive 3D audio, adaptive triggers, and a new generation of console gaming experiences.",
    image:"",
},
{
    id: 17,
    name:"Xbox Series X",
    price:28990.00,
    category:"Gaming Gear",
    description:"Xbox Series X is the most powerful Xbox ever, offering true 4K gaming, up to 120 FPS, and backward compatibility with thousands of titles.",
    image:"",
},
{
    id: 18,
    name:"Nintendo Switch OLED",
    price:17990.00,
    category:"Gaming Gear",
    description:"Nintendo Switch OLED model features a vibrant 7-inch OLED screen, enhanced audio, and versatile handheld or docked play modes.",
    image:"",
},
{
    id: 19,
    name:"Razer BlackWidow V4",
    price:9990.00,
    category:"Gaming Gear",
    description:"Razer BlackWidow V4 mechanical keyboard offers tactile switches, per-key RGB lighting, and dedicated macro controls for gamers.",
    image:"",
},
{
    id: 20,
    name:"Logitech G502 X Plus",
    price:6990.00,
    category:"Gaming Gear",
    description:"Logitech G502 X Plus gaming mouse features LIGHTSPEED wireless, customizable buttons, and HERO 25K precision sensor.",
    image:"",
},

{
    id: 21,
    name:"Anker 65W GaN Charger",
    price:2990.00,
    category:"Chargers & Power",
    description:"Anker 65W GaN charger delivers ultra-fast charging with compact design, supporting multiple devices simultaneously.",
    image:"",
},
{
    id: 22,
    name:"Belkin MagSafe Wireless Charger",
    price:3490.00,
    category:"Chargers & Power",
    description:"Belkin MagSafe charger provides secure, fast wireless charging for iPhone with magnetic alignment.",
    image:"",
},
{
    id: 23,
    name:"Baseus 20,000mAh Power Bank",
    price:2490.00,
    category:"Chargers & Power",
    description:"Baseus high-capacity power bank with 20,000mAh, fast charging, and dual output ports for multiple devices.",
    image:"",
},
{
    id: 24,
    name:"UGREEN 6-in-1 Charging Station",
    price:3990.00,
    category:"Chargers & Power",
    description:"UGREEN 6-in-1 charging station offers multiple USB-C and USB-A ports with fast charging support.",
    image:"",
},
{
    id: 25,
    name:"Aukey Car Charger",
    price:1290.00,
    category:"Chargers & Power",
    description:"Aukey car charger provides dual USB fast charging for devices while on the go.",
    image:"",
},

{
    id: 26,
    name:"Amazon Echo Dot (5th Gen)",
    price:3490.00,
    category:"Smart Home",
    description:"Echo Dot (5th Gen) with Alexa delivers clear sound, smart home controls, and hands-free assistance.",
    image:"",
},
{
    id: 27,
    name:"Google Nest Hub 2",
    price:4990.00,
    category:"Smart Home",
    description:"Google Nest Hub 2 features a 7-inch display, voice assistant, and seamless smart home device control.",
    image:"",
},
{
    id: 28,
    name:"Philips Hue Starter Kit",
    price:5990.00,
    category:"Smart Home",
    description:"Philips Hue Starter Kit offers smart color-changing LED bulbs with app and voice control.",
    image:"",
},
{
    id: 29,
    name:"Xiaomi Smart Air Purifier 4",
    price:8990.00,
    category:"Smart Home",
    description:"Xiaomi Smart Air Purifier 4 improves indoor air quality with high-precision filtration and smart app control.",
    image:"",
},
{
    id: 30,
    name:"Ring Video Doorbell 4",
    price:7990.00,
    category:"Smart Home",
    description:"Ring Video Doorbell 4 provides 1080p video, two-way audio, and real-time motion alerts for home security.",
    image:"",
},

{
    id: 31,
    name:"Spigen iPhone 15 Pro Case",
    price:1490.00,
    category:"Accessories",
    description:"Spigen case for iPhone 15 Pro offers slim protection with shock-absorbing TPU and raised edges.",
    image:"",
},
{
    id: 32,
    name:"Samsung Galaxy S24 Ultra Screen Protector",
    price:990.00,
    category:"Accessories",
    description:"Durable tempered glass screen protector designed for Samsung Galaxy S24 Ultra with anti-scratch coating.",
    image:"",
},
{
    id: 33,
    name:"Logitech MX Master 3S",
    price:5990.00,
    category:"Accessories",
    description:"Logitech MX Master 3S mouse features ultra-quiet clicks, MagSpeed scrolling, and ergonomic design.",
    image:"",
},
{
    id: 34,
    name:"WD My Passport 2TB",
    price:5990.00,
    category:"Accessories",
    description:"WD My Passport 2TB external hard drive provides reliable storage with USB 3.0 compatibility.",
    image:"",
},
{
    id: 35,
    name:"SanDisk 128GB Ultra microSD",
    price:1290.00,
    category:"Accessories",
    description:"SanDisk Ultra microSD 128GB delivers fast transfer speeds, reliable storage, and A1-rated app performance.",
    image:"",
},

];

const Categories = [
  'ALL',
  'Mobile Phones & Tablets',
  'Laptops & Computers',
  'Audio & Wearables',
  'Gaming Gears',
  'Smart Home',
  'Accessories',
];

export default Products;